module Pokeviewer
  Species.create(id: 386, name: "Deoxys")
  Species.create(id: 385, name: "Jirachi")
  Species.create(id: 384, name: "Rayquaza")
  Species.create(id: 383, name: "Groudon")
  Species.create(id: 382, name: "Kyogre")
  Species.create(id: 381, name: "Latios")
  Species.create(id: 380, name: "Latias")
  Species.create(id: 379, name: "Registeel")
  Species.create(id: 378, name: "Regice")
  Species.create(id: 377, name: "Regirock")
  Species.create(id: 376, name: "Metagross")
  Species.create(id: 375, name: "Metang")
  Species.create(id: 374, name: "Beldum")
  Species.create(id: 373, name: "Salamence")
  Species.create(id: 372, name: "Shelgon")
  Species.create(id: 371, name: "Bagon")
  Species.create(id: 370, name: "Luvdisc")
  Species.create(id: 369, name: "Relicanth")
  Species.create(id: 368, name: "Gorebyss")
  Species.create(id: 367, name: "Huntail")
  Species.create(id: 366, name: "Clamperl")
  Species.create(id: 365, name: "Walrein")
  Species.create(id: 364, name: "Sealeo")
  Species.create(id: 363, name: "Spheal")
  Species.create(id: 362, name: "Glalie")
  Species.create(id: 361, name: "Snorunt")
  Species.create(id: 360, name: "Wynaut")
  Species.create(id: 359, name: "Absol")
  Species.create(id: 358, name: "Chimecho")
  Species.create(id: 357, name: "Tropius")
  Species.create(id: 356, name: "Dusclops")
  Species.create(id: 355, name: "Duskull")
  Species.create(id: 354, name: "Banette")
  Species.create(id: 353, name: "Shuppet")
  Species.create(id: 352, name: "Kecleon")
  Species.create(id: 351, name: "Castform")
  Species.create(id: 350, name: "Milotic")
  Species.create(id: 349, name: "Feebas")
  Species.create(id: 348, name: "Armaldo")
  Species.create(id: 347, name: "Anorith")
  Species.create(id: 346, name: "Cradily")
  Species.create(id: 345, name: "Lileep")
  Species.create(id: 344, name: "Claydol")
  Species.create(id: 343, name: "Baltoy")
  Species.create(id: 342, name: "Crawdaunt")
  Species.create(id: 341, name: "Corphish")
  Species.create(id: 340, name: "Whiscash")
  Species.create(id: 339, name: "Barboach")
  Species.create(id: 338, name: "Solrock")
  Species.create(id: 337, name: "Lunatone")
  Species.create(id: 336, name: "Seviper")
  Species.create(id: 335, name: "Zangoose")
  Species.create(id: 334, name: "Altaria")
  Species.create(id: 333, name: "Swablu")
  Species.create(id: 332, name: "Cacturne")
  Species.create(id: 331, name: "Cacnea")
  Species.create(id: 330, name: "Flygon")
  Species.create(id: 329, name: "Vibrava")
  Species.create(id: 328, name: "Trapinch")
  Species.create(id: 327, name: "Spinda")
  Species.create(id: 326, name: "Grumpig")
  Species.create(id: 325, name: "Spoink")
  Species.create(id: 324, name: "Torkoal")
  Species.create(id: 323, name: "Camerupt")
  Species.create(id: 322, name: "Numel")
  Species.create(id: 321, name: "Wailord")
  Species.create(id: 320, name: "Wailmer")
  Species.create(id: 319, name: "Sharpedo")
  Species.create(id: 318, name: "Carvanha")
  Species.create(id: 317, name: "Swalot")
  Species.create(id: 316, name: "Gulpin")
  Species.create(id: 315, name: "Roselia")
  Species.create(id: 314, name: "Illumise")
  Species.create(id: 313, name: "Volbeat")
  Species.create(id: 312, name: "Minun")
  Species.create(id: 311, name: "Plusle")
  Species.create(id: 310, name: "Manectric")
  Species.create(id: 309, name: "Electrike")
  Species.create(id: 308, name: "Medicham")
  Species.create(id: 307, name: "Meditite")
  Species.create(id: 306, name: "Aggron")
  Species.create(id: 305, name: "Lairon")
  Species.create(id: 304, name: "Aron")
  Species.create(id: 303, name: "Mawile")
  Species.create(id: 302, name: "Sableye")
  Species.create(id: 301, name: "Delcatty")
  Species.create(id: 300, name: "Skitty")
  Species.create(id: 299, name: "Nosepass")
  Species.create(id: 298, name: "Azurill")
  Species.create(id: 297, name: "Hariyama")
  Species.create(id: 296, name: "Makuhita")
  Species.create(id: 295, name: "Exploud")
  Species.create(id: 294, name: "Loudred")
  Species.create(id: 293, name: "Whismur")
  Species.create(id: 292, name: "Shedinja")
  Species.create(id: 291, name: "Ninjask")
  Species.create(id: 290, name: "Nincada")
  Species.create(id: 289, name: "Slaking")
  Species.create(id: 288, name: "Vigoroth")
  Species.create(id: 287, name: "Slakoth")
  Species.create(id: 286, name: "Breloom")
  Species.create(id: 285, name: "Shroomish")
  Species.create(id: 284, name: "Masquerain")
  Species.create(id: 283, name: "Surskit")
  Species.create(id: 282, name: "Gardevoir")
  Species.create(id: 281, name: "Kirlia")
  Species.create(id: 280, name: "Ralts")
  Species.create(id: 279, name: "Pelipper")
  Species.create(id: 278, name: "Wingull")
  Species.create(id: 277, name: "Swellow")
  Species.create(id: 276, name: "Taillow")
  Species.create(id: 275, name: "Shiftry")
  Species.create(id: 274, name: "Nuzleaf")
  Species.create(id: 273, name: "Seedot")
  Species.create(id: 272, name: "Ludicolo")
  Species.create(id: 271, name: "Lombre")
  Species.create(id: 270, name: "Lotad")
  Species.create(id: 269, name: "Dustox")
  Species.create(id: 268, name: "Cascoon")
  Species.create(id: 267, name: "Beautifly")
  Species.create(id: 266, name: "Silcoon")
  Species.create(id: 265, name: "Wurmple")
  Species.create(id: 264, name: "Linoone")
  Species.create(id: 263, name: "Zigzagoon")
  Species.create(id: 262, name: "Mightyena")
  Species.create(id: 261, name: "Poochyena")
  Species.create(id: 260, name: "Swampert")
  Species.create(id: 259, name: "Marshtomp")
  Species.create(id: 258, name: "Mudkip")
  Species.create(id: 257, name: "Blaziken")
  Species.create(id: 256, name: "Combusken")
  Species.create(id: 255, name: "Torchic")
  Species.create(id: 254, name: "Sceptile")
  Species.create(id: 253, name: "Grovyle")
  Species.create(id: 252, name: "Treecko")
  Species.create(id: 251, name: "Celebi")
  Species.create(id: 250, name: "Ho-Oh")
  Species.create(id: 249, name: "Lugia")
  Species.create(id: 248, name: "Tyranitar")
  Species.create(id: 247, name: "Pupitar")
  Species.create(id: 246, name: "Larvitar")
  Species.create(id: 245, name: "Suicune")
  Species.create(id: 244, name: "Entei")
  Species.create(id: 243, name: "Raikou")
  Species.create(id: 242, name: "Blissey")
  Species.create(id: 241, name: "Miltank")
  Species.create(id: 240, name: "Magby")
  Species.create(id: 239, name: "Elekid")
  Species.create(id: 238, name: "Smoochum")
  Species.create(id: 237, name: "Hitmontop")
  Species.create(id: 236, name: "Tyrogue")
  Species.create(id: 235, name: "Smeargle")
  Species.create(id: 234, name: "Stantler")
  Species.create(id: 233, name: "Porygon2")
  Species.create(id: 232, name: "Donphan")
  Species.create(id: 231, name: "Phanpy")
  Species.create(id: 230, name: "Kingdra")
  Species.create(id: 229, name: "Houndoom")
  Species.create(id: 228, name: "Houndour")
  Species.create(id: 227, name: "Skarmory")
  Species.create(id: 226, name: "Mantine")
  Species.create(id: 225, name: "Delibird")
  Species.create(id: 224, name: "Octillery")
  Species.create(id: 223, name: "Remoraid")
  Species.create(id: 222, name: "Corsola")
  Species.create(id: 221, name: "Piloswine")
  Species.create(id: 220, name: "Swinub")
  Species.create(id: 219, name: "Magcargo")
  Species.create(id: 218, name: "Slugma")
  Species.create(id: 217, name: "Ursaring")
  Species.create(id: 216, name: "Teddiursa")
  Species.create(id: 215, name: "Sneasel")
  Species.create(id: 214, name: "Heracross")
  Species.create(id: 213, name: "Shuckle")
  Species.create(id: 212, name: "Scizor")
  Species.create(id: 211, name: "Qwilfish")
  Species.create(id: 210, name: "Granbull")
  Species.create(id: 209, name: "Snubbull")
  Species.create(id: 208, name: "Steelix")
  Species.create(id: 207, name: "Gligar")
  Species.create(id: 206, name: "Dunsparce")
  Species.create(id: 205, name: "Forretress")
  Species.create(id: 204, name: "Pineco")
  Species.create(id: 203, name: "Girafarig")
  Species.create(id: 202, name: "Wobbuffet")
  Species.create(id: 201, name: "Unown")
  Species.create(id: 200, name: "Misdreavus")
  Species.create(id: 199, name: "Slowking")
  Species.create(id: 198, name: "Murkrow")
  Species.create(id: 197, name: "Umbreon")
  Species.create(id: 196, name: "Espeon")
  Species.create(id: 195, name: "Quagsire")
  Species.create(id: 194, name: "Wooper")
  Species.create(id: 193, name: "Yanma")
  Species.create(id: 192, name: "Sunflora")
  Species.create(id: 191, name: "Sunkern")
  Species.create(id: 190, name: "Aipom")
  Species.create(id: 189, name: "Jumpluff")
  Species.create(id: 188, name: "Skiploom")
  Species.create(id: 187, name: "Hoppip")
  Species.create(id: 186, name: "Politoed")
  Species.create(id: 185, name: "Sudowoodo")
  Species.create(id: 184, name: "Azumarill")
  Species.create(id: 183, name: "Marill")
  Species.create(id: 182, name: "Bellossom")
  Species.create(id: 181, name: "Ampharos")
  Species.create(id: 180, name: "Flaaffy")
  Species.create(id: 179, name: "Mareep")
  Species.create(id: 178, name: "Xatu")
  Species.create(id: 177, name: "Natu")
  Species.create(id: 176, name: "Togetic")
  Species.create(id: 175, name: "Togepi")
  Species.create(id: 174, name: "Igglybuff")
  Species.create(id: 173, name: "Cleffa")
  Species.create(id: 172, name: "Pichu")
  Species.create(id: 171, name: "Lanturn")
  Species.create(id: 170, name: "Chinchou")
  Species.create(id: 169, name: "Crobat")
  Species.create(id: 168, name: "Ariados")
  Species.create(id: 167, name: "Spinarak")
  Species.create(id: 166, name: "Ledian")
  Species.create(id: 165, name: "Ledyba")
  Species.create(id: 164, name: "Noctowl")
  Species.create(id: 163, name: "Hoothoot")
  Species.create(id: 162, name: "Furret")
  Species.create(id: 161, name: "Sentret")
  Species.create(id: 160, name: "Feraligatr")
  Species.create(id: 159, name: "Croconaw")
  Species.create(id: 158, name: "Totodile")
  Species.create(id: 157, name: "Typhlosion")
  Species.create(id: 156, name: "Quilava")
  Species.create(id: 155, name: "Cyndaquil")
  Species.create(id: 154, name: "Meganium")
  Species.create(id: 153, name: "Bayleef")
  Species.create(id: 152, name: "Chikorita")
  Species.create(id: 151, name: "Mew")
  Species.create(id: 150, name: "Mewtwo")
  Species.create(id: 149, name: "Dragonite")
  Species.create(id: 148, name: "Dragonair")
  Species.create(id: 147, name: "Dratini")
  Species.create(id: 146, name: "Moltres")
  Species.create(id: 145, name: "Zapdos")
  Species.create(id: 144, name: "Articuno")
  Species.create(id: 143, name: "Snorlax")
  Species.create(id: 142, name: "Aerodactyl")
  Species.create(id: 141, name: "Kabutops")
  Species.create(id: 140, name: "Kabuto")
  Species.create(id: 139, name: "Omastar")
  Species.create(id: 138, name: "Omanyte")
  Species.create(id: 137, name: "Porygon")
  Species.create(id: 136, name: "Flareon")
  Species.create(id: 135, name: "Jolteon")
  Species.create(id: 134, name: "Vaporeon")
  Species.create(id: 133, name: "Eevee")
  Species.create(id: 132, name: "Ditto")
  Species.create(id: 131, name: "Lapras")
  Species.create(id: 130, name: "Gyarados")
  Species.create(id: 129, name: "Magikarp")
  Species.create(id: 128, name: "Tauros")
  Species.create(id: 127, name: "Pinsir")
  Species.create(id: 126, name: "Magmar")
  Species.create(id: 125, name: "Electabuzz")
  Species.create(id: 124, name: "Jynx")
  Species.create(id: 123, name: "Scyther")
  Species.create(id: 122, name: "Mr. Mime")
  Species.create(id: 121, name: "Starmie")
  Species.create(id: 120, name: "Staryu")
  Species.create(id: 119, name: "Seaking")
  Species.create(id: 118, name: "Goldeen")
  Species.create(id: 117, name: "Seadra")
  Species.create(id: 116, name: "Horsea")
  Species.create(id: 115, name: "Kangaskhan")
  Species.create(id: 114, name: "Tangela")
  Species.create(id: 113, name: "Chansey")
  Species.create(id: 112, name: "Rhydon")
  Species.create(id: 111, name: "Rhyhorn")
  Species.create(id: 110, name: "Weezing")
  Species.create(id: 109, name: "Koffing")
  Species.create(id: 108, name: "Lickitung")
  Species.create(id: 107, name: "Hitmonchan")
  Species.create(id: 106, name: "Hitmonlee")
  Species.create(id: 105, name: "Marowak")
  Species.create(id: 104, name: "Cubone")
  Species.create(id: 103, name: "Exeggutor")
  Species.create(id: 102, name: "Exeggcute")
  Species.create(id: 101, name: "Electrode")
  Species.create(id: 100, name: "Voltorb")
  Species.create(id: 99, name: "Kingler")
  Species.create(id: 98, name: "Krabby")
  Species.create(id: 97, name: "Hypno")
  Species.create(id: 96, name: "Drowzee")
  Species.create(id: 95, name: "Onix")
  Species.create(id: 94, name: "Gengar")
  Species.create(id: 93, name: "Haunter")
  Species.create(id: 92, name: "Gastly")
  Species.create(id: 91, name: "Cloyster")
  Species.create(id: 90, name: "Shellder")
  Species.create(id: 89, name: "Muk")
  Species.create(id: 88, name: "Grimer")
  Species.create(id: 87, name: "Dewgong")
  Species.create(id: 86, name: "Seel")
  Species.create(id: 85, name: "Dodrio")
  Species.create(id: 84, name: "Doduo")
  Species.create(id: 83, name: "Farfetch'd")
  Species.create(id: 82, name: "Magneton")
  Species.create(id: 81, name: "Magnemite")
  Species.create(id: 80, name: "Slowbro")
  Species.create(id: 79, name: "Slowpoke")
  Species.create(id: 78, name: "Rapidash")
  Species.create(id: 77, name: "Ponyta")
  Species.create(id: 76, name: "Golem")
  Species.create(id: 75, name: "Graveler")
  Species.create(id: 74, name: "Geodude")
  Species.create(id: 73, name: "Tentacruel")
  Species.create(id: 72, name: "Tentacool")
  Species.create(id: 71, name: "Victreebel")
  Species.create(id: 70, name: "Weepinbell")
  Species.create(id: 69, name: "Bellsprout")
  Species.create(id: 68, name: "Machamp")
  Species.create(id: 67, name: "Machoke")
  Species.create(id: 66, name: "Machop")
  Species.create(id: 65, name: "Alakazam")
  Species.create(id: 64, name: "Kadabra")
  Species.create(id: 63, name: "Abra")
  Species.create(id: 62, name: "Poliwrath")
  Species.create(id: 61, name: "Poliwhirl")
  Species.create(id: 60, name: "Poliwag")
  Species.create(id: 59, name: "Arcanine")
  Species.create(id: 58, name: "Growlithe")
  Species.create(id: 57, name: "Primeape")
  Species.create(id: 56, name: "Mankey")
  Species.create(id: 55, name: "Golduck")
  Species.create(id: 54, name: "Psyduck")
  Species.create(id: 53, name: "Persian")
  Species.create(id: 52, name: "Meowth")
  Species.create(id: 51, name: "Dugtrio")
  Species.create(id: 50, name: "Diglett")
  Species.create(id: 49, name: "Venomoth")
  Species.create(id: 48, name: "Venonat")
  Species.create(id: 47, name: "Parasect")
  Species.create(id: 46, name: "Paras")
  Species.create(id: 45, name: "Vileplume")
  Species.create(id: 44, name: "Gloom")
  Species.create(id: 43, name: "Oddish")
  Species.create(id: 42, name: "Golbat")
  Species.create(id: 41, name: "Zubat")
  Species.create(id: 40, name: "Wigglytuff")
  Species.create(id: 39, name: "Jigglypuff")
  Species.create(id: 38, name: "Ninetales")
  Species.create(id: 37, name: "Vulpix")
  Species.create(id: 36, name: "Clefable")
  Species.create(id: 35, name: "Clefairy")
  Species.create(id: 34, name: "Nidoking")
  Species.create(id: 33, name: "Nidorino")
  Species.create(id: 32, name: "Nidoran♂")
  Species.create(id: 31, name: "Nidoqueen")
  Species.create(id: 30, name: "Nidorina")
  Species.create(id: 29, name: "Nidoran♀")
  Species.create(id: 28, name: "Sandslash")
  Species.create(id: 27, name: "Sandshrew")
  Species.create(id: 26, name: "Raichu")
  Species.create(id: 25, name: "Pikachu")
  Species.create(id: 24, name: "Arbok")
  Species.create(id: 23, name: "Ekans")
  Species.create(id: 22, name: "Fearow")
  Species.create(id: 21, name: "Spearow")
  Species.create(id: 20, name: "Raticate")
  Species.create(id: 19, name: "Rattata")
  Species.create(id: 18, name: "Pidgeot")
  Species.create(id: 17, name: "Pidgeotto")
  Species.create(id: 16, name: "Pidgey")
  Species.create(id: 15, name: "Beedrill")
  Species.create(id: 14, name: "Kakuna")
  Species.create(id: 13, name: "Weedle")
  Species.create(id: 12, name: "Butterfree")
  Species.create(id: 11, name: "Metapod")
  Species.create(id: 10, name: "Caterpie")
  Species.create(id: 9, name: "Blastoise")
  Species.create(id: 8, name: "Wartortle")
  Species.create(id: 7, name: "Squirtle")
  Species.create(id: 6, name: "Charizard")
  Species.create(id: 5, name: "Charmeleon")
  Species.create(id: 4, name: "Charmander")
  Species.create(id: 3, name: "Venusaur")
  Species.create(id: 2, name: "Ivysaur")
  Species.create(id: 1, name: "Bulbasaur")

  Move.create(id: 354, name: "Psycho Boost", pp: 5)
  Move.create(id: 353, name: "Doom Desire", pp: 5)
  Move.create(id: 352, name: "Water Pulse", pp: 20)
  Move.create(id: 351, name: "Shock Wave", pp: 20)
  Move.create(id: 350, name: "Rock Blast", pp: 10)
  Move.create(id: 349, name: "Dragon Dance", pp: 20)
  Move.create(id: 348, name: "Leaf Blade", pp: 15)
  Move.create(id: 347, name: "Calm Mind", pp: 20)
  Move.create(id: 346, name: "Water Sport", pp: 15)
  Move.create(id: 345, name: "Magical Leaf", pp: 20)
  Move.create(id: 344, name: "Volt Tackle", pp: 15)
  Move.create(id: 343, name: "Covet", pp: 25)
  Move.create(id: 342, name: "Poison Tail", pp: 25)
  Move.create(id: 341, name: "Mud Shot", pp: 15)
  Move.create(id: 340, name: "Bounce", pp: 5)
  Move.create(id: 339, name: "Bulk Up", pp: 20)
  Move.create(id: 338, name: "Frenzy Plant", pp: 5)
  Move.create(id: 337, name: "Dragon Claw", pp: 15)
  Move.create(id: 336, name: "Howl", pp: 40)
  Move.create(id: 335, name: "Block", pp: 5)
  Move.create(id: 334, name: "Iron Defense", pp: 15)
  Move.create(id: 333, name: "Icicle Spear", pp: 30)
  Move.create(id: 332, name: "Aerial Ace", pp: 20)
  Move.create(id: 331, name: "Bullet Seed", pp: 30)
  Move.create(id: 330, name: "Muddy Water", pp: 10)
  Move.create(id: 329, name: "Sheer Cold", pp: 5)
  Move.create(id: 328, name: "Sand Tomb", pp: 15)
  Move.create(id: 327, name: "Sky Uppercut", pp: 15)
  Move.create(id: 326, name: "Extrasensory", pp: 20)
  Move.create(id: 325, name: "Shadow Punch", pp: 20)
  Move.create(id: 324, name: "Signal Beam", pp: 15)
  Move.create(id: 323, name: "Water Spout", pp: 5)
  Move.create(id: 322, name: "Cosmic Power", pp: 20)
  Move.create(id: 321, name: "Tickle", pp: 20)
  Move.create(id: 320, name: "Grass Whistle", pp: 15)
  Move.create(id: 319, name: "Metal Sound", pp: 40)
  Move.create(id: 318, name: "Silver Wind", pp: 5)
  Move.create(id: 317, name: "Rock Tomb", pp: 15)
  Move.create(id: 316, name: "Odor Sleuth", pp: 40)
  Move.create(id: 315, name: "Overheat", pp: 5)
  Move.create(id: 314, name: "Air Cutter", pp: 25)
  Move.create(id: 313, name: "Fake Tears", pp: 20)
  Move.create(id: 312, name: "Aromatherapy", pp: 5)
  Move.create(id: 311, name: "Weather Ball", pp: 10)
  Move.create(id: 310, name: "Astonish", pp: 15)
  Move.create(id: 309, name: "Meteor Mash", pp: 10)
  Move.create(id: 308, name: "Hydro Cannon", pp: 5)
  Move.create(id: 307, name: "Blast Burn", pp: 5)
  Move.create(id: 306, name: "Crush Claw", pp: 10)
  Move.create(id: 305, name: "Poison Fang", pp: 15)
  Move.create(id: 304, name: "Hyper Voice", pp: 10)
  Move.create(id: 303, name: "Slack Off", pp: 10)
  Move.create(id: 302, name: "Needle Arm", pp: 15)
  Move.create(id: 301, name: "Ice Ball", pp: 20)
  Move.create(id: 300, name: "Mud Sport", pp: 15)
  Move.create(id: 299, name: "Blaze Kick", pp: 10)
  Move.create(id: 298, name: "Teeter Dance", pp: 20)
  Move.create(id: 297, name: "Feather Dance", pp: 15)
  Move.create(id: 296, name: "Mist Ball", pp: 5)
  Move.create(id: 295, name: "Luster Purge", pp: 5)
  Move.create(id: 294, name: "Tail Glow", pp: 20)
  Move.create(id: 293, name: "Camouflage", pp: 20)
  Move.create(id: 292, name: "Arm Thrust", pp: 20)
  Move.create(id: 291, name: "Dive", pp: 10)
  Move.create(id: 290, name: "Secret Power", pp: 20)
  Move.create(id: 289, name: "Snatch", pp: 10)
  Move.create(id: 288, name: "Grudge", pp: 5)
  Move.create(id: 287, name: "Refresh", pp: 20)
  Move.create(id: 286, name: "Imprison", pp: 10)
  Move.create(id: 285, name: "Skill Swap", pp: 10)
  Move.create(id: 284, name: "Eruption", pp: 5)
  Move.create(id: 283, name: "Endeavor", pp: 5)
  Move.create(id: 282, name: "Knock Off", pp: 20)
  Move.create(id: 281, name: "Yawn", pp: 10)
  Move.create(id: 280, name: "Brick Break", pp: 15)
  Move.create(id: 279, name: "Revenge", pp: 10)
  Move.create(id: 278, name: "Recycle", pp: 10)
  Move.create(id: 277, name: "Magic Coat", pp: 15)
  Move.create(id: 276, name: "Superpower", pp: 5)
  Move.create(id: 275, name: "Ingrain", pp: 20)
  Move.create(id: 274, name: "Assist", pp: 20)
  Move.create(id: 273, name: "Wish", pp: 10)
  Move.create(id: 272, name: "Role Play", pp: 10)
  Move.create(id: 271, name: "Trick", pp: 10)
  Move.create(id: 270, name: "Helping Hand", pp: 20)
  Move.create(id: 269, name: "Taunt", pp: 20)
  Move.create(id: 268, name: "Charge", pp: 20)
  Move.create(id: 267, name: "Nature Power", pp: 20)
  Move.create(id: 266, name: "Follow Me", pp: 20)
  Move.create(id: 265, name: "Smelling Salts", pp: 10)
  Move.create(id: 264, name: "Focus Punch", pp: 20)
  Move.create(id: 263, name: "Facade", pp: 20)
  Move.create(id: 262, name: "Memento", pp: 10)
  Move.create(id: 261, name: "Will-O-Wisp", pp: 15)
  Move.create(id: 260, name: "Flatter", pp: 15)
  Move.create(id: 259, name: "Torment", pp: 15)
  Move.create(id: 258, name: "Hail", pp: 10)
  Move.create(id: 257, name: "Heat Wave", pp: 10)
  Move.create(id: 256, name: "Swallow", pp: 10)
  Move.create(id: 255, name: "Spit Up", pp: 10)
  Move.create(id: 254, name: "Stockpile", pp: 10)
  Move.create(id: 253, name: "Uproar", pp: 10)
  Move.create(id: 252, name: "Fake Out", pp: 10)
  Move.create(id: 251, name: "Beat Up", pp: 10)
  Move.create(id: 250, name: "Whirlpool", pp: 15)
  Move.create(id: 249, name: "Rock Smash", pp: 15)
  Move.create(id: 248, name: "Future Sight", pp: 15)
  Move.create(id: 247, name: "Shadow Ball", pp: 15)
  Move.create(id: 246, name: "Ancient Power", pp: 5)
  Move.create(id: 245, name: "Extreme Speed", pp: 5)
  Move.create(id: 244, name: "Psych Up", pp: 10)
  Move.create(id: 243, name: "Mirror Coat", pp: 20)
  Move.create(id: 242, name: "Crunch", pp: 15)
  Move.create(id: 241, name: "Sunny Day", pp: 5)
  Move.create(id: 240, name: "Rain Dance", pp: 5)
  Move.create(id: 239, name: "Twister", pp: 20)
  Move.create(id: 238, name: "Cross Chop", pp: 5)
  Move.create(id: 237, name: "Hidden Power", pp: 15)
  Move.create(id: 236, name: "Moonlight", pp: 5)
  Move.create(id: 235, name: "Synthesis", pp: 5)
  Move.create(id: 234, name: "Morning Sun", pp: 5)
  Move.create(id: 233, name: "Vital Throw", pp: 10)
  Move.create(id: 232, name: "Metal Claw", pp: 35)
  Move.create(id: 231, name: "Iron Tail", pp: 15)
  Move.create(id: 230, name: "Sweet Scent", pp: 20)
  Move.create(id: 229, name: "Rapid Spin", pp: 40)
  Move.create(id: 228, name: "Pursuit", pp: 20)
  Move.create(id: 227, name: "Encore", pp: 5)
  Move.create(id: 226, name: "Baton Pass", pp: 40)
  Move.create(id: 225, name: "Dragon Breath", pp: 20)
  Move.create(id: 224, name: "Megahorn", pp: 10)
  Move.create(id: 223, name: "Dynamic Punch", pp: 5)
  Move.create(id: 222, name: "Magnitude", pp: 30)
  Move.create(id: 221, name: "Sacred Fire", pp: 5)
  Move.create(id: 220, name: "Pain Split", pp: 20)
  Move.create(id: 219, name: "Safeguard", pp: 25)
  Move.create(id: 218, name: "Frustration", pp: 20)
  Move.create(id: 217, name: "Present", pp: 15)
  Move.create(id: 216, name: "Return", pp: 20)
  Move.create(id: 215, name: "Heal Bell", pp: 5)
  Move.create(id: 214, name: "Sleep Talk", pp: 10)
  Move.create(id: 213, name: "Attract", pp: 15)
  Move.create(id: 212, name: "Mean Look", pp: 5)
  Move.create(id: 211, name: "Steel Wing", pp: 25)
  Move.create(id: 210, name: "Fury Cutter", pp: 20)
  Move.create(id: 209, name: "Spark", pp: 20)
  Move.create(id: 208, name: "Milk Drink", pp: 10)
  Move.create(id: 207, name: "Swagger", pp: 15)
  Move.create(id: 206, name: "False Swipe", pp: 40)
  Move.create(id: 205, name: "Rollout", pp: 20)
  Move.create(id: 204, name: "Charm", pp: 20)
  Move.create(id: 203, name: "Endure", pp: 10)
  Move.create(id: 202, name: "Giga Drain", pp: 5)
  Move.create(id: 201, name: "Sandstorm", pp: 10)
  Move.create(id: 200, name: "Outrage", pp: 15)
  Move.create(id: 199, name: "Lock-On", pp: 5)
  Move.create(id: 198, name: "Bone Rush", pp: 10)
  Move.create(id: 197, name: "Detect", pp: 5)
  Move.create(id: 196, name: "Icy Wind", pp: 15)
  Move.create(id: 195, name: "Perish Song", pp: 5)
  Move.create(id: 194, name: "Destiny Bond", pp: 5)
  Move.create(id: 193, name: "Foresight", pp: 40)
  Move.create(id: 192, name: "Zap Cannon", pp: 5)
  Move.create(id: 191, name: "Spikes", pp: 20)
  Move.create(id: 190, name: "Octazooka", pp: 10)
  Move.create(id: 189, name: "Mud-Slap", pp: 10)
  Move.create(id: 188, name: "Sludge Bomb", pp: 10)
  Move.create(id: 187, name: "Belly Drum", pp: 10)
  Move.create(id: 186, name: "Sweet Kiss", pp: 10)
  Move.create(id: 185, name: "Feint Attack", pp: 20)
  Move.create(id: 184, name: "Scary Face", pp: 10)
  Move.create(id: 183, name: "Mach Punch", pp: 30)
  Move.create(id: 182, name: "Protect", pp: 10)
  Move.create(id: 181, name: "Powder Snow", pp: 25)
  Move.create(id: 180, name: "Spite", pp: 10)
  Move.create(id: 179, name: "Reversal", pp: 15)
  Move.create(id: 178, name: "Cotton Spore", pp: 40)
  Move.create(id: 177, name: "Aeroblast", pp: 5)
  Move.create(id: 176, name: "Conversion 2", pp: 30)
  Move.create(id: 175, name: "Flail", pp: 15)
  Move.create(id: 174, name: "Curse", pp: 10)
  Move.create(id: 173, name: "Snore", pp: 15)
  Move.create(id: 172, name: "Flame Wheel", pp: 25)
  Move.create(id: 171, name: "Nightmare", pp: 15)
  Move.create(id: 170, name: "Mind Reader", pp: 40)
  Move.create(id: 169, name: "Spider Web", pp: 10)
  Move.create(id: 168, name: "Thief", pp: 25)
  Move.create(id: 167, name: "Triple Kick", pp: 10)
  Move.create(id: 166, name: "Sketch", pp: 1)
  Move.create(id: 165, name: "Struggle", pp: 0)
  Move.create(id: 164, name: "Substitute", pp: 10)
  Move.create(id: 163, name: "Slash", pp: 20)
  Move.create(id: 162, name: "Super Fang", pp: 10)
  Move.create(id: 161, name: "Tri Attack", pp: 10)
  Move.create(id: 160, name: "Conversion", pp: 30)
  Move.create(id: 159, name: "Sharpen", pp: 30)
  Move.create(id: 158, name: "Hyper Fang", pp: 15)
  Move.create(id: 157, name: "Rock Slide", pp: 10)
  Move.create(id: 156, name: "Rest", pp: 10)
  Move.create(id: 155, name: "Bonemerang", pp: 10)
  Move.create(id: 154, name: "Fury Swipes", pp: 15)
  Move.create(id: 153, name: "Explosion", pp: 5)
  Move.create(id: 152, name: "Crabhammer", pp: 10)
  Move.create(id: 151, name: "Acid Armor", pp: 20)
  Move.create(id: 150, name: "Splash", pp: 40)
  Move.create(id: 149, name: "Psywave", pp: 15)
  Move.create(id: 148, name: "Flash", pp: 20)
  Move.create(id: 147, name: "Spore", pp: 15)
  Move.create(id: 146, name: "Dizzy Punch", pp: 10)
  Move.create(id: 145, name: "Bubble", pp: 30)
  Move.create(id: 144, name: "Transform", pp: 10)
  Move.create(id: 143, name: "Sky Attack", pp: 5)
  Move.create(id: 142, name: "Lovely Kiss", pp: 10)
  Move.create(id: 141, name: "Leech Life", pp: 15)
  Move.create(id: 140, name: "Barrage", pp: 20)
  Move.create(id: 139, name: "Poison Gas", pp: 40)
  Move.create(id: 138, name: "Dream Eater", pp: 15)
  Move.create(id: 137, name: "Glare", pp: 30)
  Move.create(id: 136, name: "High Jump Kick", pp: 20)
  Move.create(id: 135, name: "Soft-Boiled", pp: 10)
  Move.create(id: 134, name: "Kinesis", pp: 15)
  Move.create(id: 133, name: "Amnesia", pp: 20)
  Move.create(id: 132, name: "Constrict", pp: 35)
  Move.create(id: 131, name: "Spike Cannon", pp: 15)
  Move.create(id: 130, name: "Skull Bash", pp: 10)
  Move.create(id: 129, name: "Swift", pp: 20)
  Move.create(id: 128, name: "Clamp", pp: 10)
  Move.create(id: 127, name: "Waterfall", pp: 15)
  Move.create(id: 126, name: "Fire Blast", pp: 5)
  Move.create(id: 125, name: "Bone Club", pp: 20)
  Move.create(id: 124, name: "Sludge", pp: 20)
  Move.create(id: 123, name: "Smog", pp: 20)
  Move.create(id: 122, name: "Lick", pp: 30)
  Move.create(id: 121, name: "Egg Bomb", pp: 10)
  Move.create(id: 120, name: "Self-Destruct", pp: 5)
  Move.create(id: 119, name: "Mirror Move", pp: 20)
  Move.create(id: 118, name: "Metronome", pp: 10)
  Move.create(id: 117, name: "Bide", pp: 10)
  Move.create(id: 116, name: "Focus Energy", pp: 30)
  Move.create(id: 115, name: "Reflect", pp: 20)
  Move.create(id: 114, name: "Haze", pp: 30)
  Move.create(id: 113, name: "Light Screen", pp: 30)
  Move.create(id: 112, name: "Barrier", pp: 20)
  Move.create(id: 111, name: "Defense Curl", pp: 40)
  Move.create(id: 110, name: "Withdraw", pp: 40)
  Move.create(id: 109, name: "Confuse Ray", pp: 10)
  Move.create(id: 108, name: "Smokescreen", pp: 20)
  Move.create(id: 107, name: "Minimize", pp: 10)
  Move.create(id: 106, name: "Harden", pp: 30)
  Move.create(id: 105, name: "Recover", pp: 20)
  Move.create(id: 104, name: "Double Team", pp: 15)
  Move.create(id: 103, name: "Screech", pp: 40)
  Move.create(id: 102, name: "Mimic", pp: 10)
  Move.create(id: 101, name: "Night Shade", pp: 15)
  Move.create(id: 100, name: "Teleport", pp: 20)
  Move.create(id: 99, name: "Rage", pp: 20)
  Move.create(id: 98, name: "Quick Attack", pp: 30)
  Move.create(id: 97, name: "Agility", pp: 30)
  Move.create(id: 96, name: "Meditate", pp: 40)
  Move.create(id: 95, name: "Hypnosis", pp: 20)
  Move.create(id: 94, name: "Psychic", pp: 10)
  Move.create(id: 93, name: "Confusion", pp: 25)
  Move.create(id: 92, name: "Toxic", pp: 10)
  Move.create(id: 91, name: "Dig", pp: 10)
  Move.create(id: 90, name: "Fissure", pp: 5)
  Move.create(id: 89, name: "Earthquake", pp: 10)
  Move.create(id: 88, name: "Rock Throw", pp: 15)
  Move.create(id: 87, name: "Thunder", pp: 10)
  Move.create(id: 86, name: "Thunder Wave", pp: 20)
  Move.create(id: 85, name: "Thunderbolt", pp: 15)
  Move.create(id: 84, name: "Thunder Shock", pp: 30)
  Move.create(id: 83, name: "Fire Spin", pp: 15)
  Move.create(id: 82, name: "Dragon Rage", pp: 10)
  Move.create(id: 81, name: "String Shot", pp: 40)
  Move.create(id: 80, name: "Petal Dance", pp: 20)
  Move.create(id: 79, name: "Sleep Powder", pp: 15)
  Move.create(id: 78, name: "Stun Spore", pp: 30)
  Move.create(id: 77, name: "Poison Powder", pp: 35)
  Move.create(id: 76, name: "Solar Beam", pp: 10)
  Move.create(id: 75, name: "Razor Leaf", pp: 25)
  Move.create(id: 74, name: "Growth", pp: 20)
  Move.create(id: 73, name: "Leech Seed", pp: 10)
  Move.create(id: 72, name: "Mega Drain", pp: 10)
  Move.create(id: 71, name: "Absorb", pp: 20)
  Move.create(id: 70, name: "Strength", pp: 15)
  Move.create(id: 69, name: "Seismic Toss", pp: 20)
  Move.create(id: 68, name: "Counter", pp: 20)
  Move.create(id: 67, name: "Low Kick", pp: 20)
  Move.create(id: 66, name: "Submission", pp: 20)
  Move.create(id: 65, name: "Drill Peck", pp: 20)
  Move.create(id: 64, name: "Peck", pp: 35)
  Move.create(id: 63, name: "Hyper Beam", pp: 5)
  Move.create(id: 62, name: "Aurora Beam", pp: 20)
  Move.create(id: 61, name: "Bubble Beam", pp: 20)
  Move.create(id: 60, name: "Psybeam", pp: 20)
  Move.create(id: 59, name: "Blizzard", pp: 5)
  Move.create(id: 58, name: "Ice Beam", pp: 10)
  Move.create(id: 57, name: "Surf", pp: 15)
  Move.create(id: 56, name: "Hydro Pump", pp: 5)
  Move.create(id: 55, name: "Water Gun", pp: 25)
  Move.create(id: 54, name: "Mist", pp: 30)
  Move.create(id: 53, name: "Flamethrower", pp: 15)
  Move.create(id: 52, name: "Ember", pp: 25)
  Move.create(id: 51, name: "Acid", pp: 30)
  Move.create(id: 50, name: "Disable", pp: 20)
  Move.create(id: 49, name: "Sonic Boom", pp: 20)
  Move.create(id: 48, name: "Supersonic", pp: 20)
  Move.create(id: 47, name: "Sing", pp: 15)
  Move.create(id: 46, name: "Roar", pp: 20)
  Move.create(id: 45, name: "Growl", pp: 40)
  Move.create(id: 44, name: "Bite", pp: 25)
  Move.create(id: 43, name: "Leer", pp: 30)
  Move.create(id: 42, name: "Pin Missile", pp: 20)
  Move.create(id: 41, name: "Twineedle", pp: 20)
  Move.create(id: 40, name: "Poison Sting", pp: 35)
  Move.create(id: 39, name: "Tail Whip", pp: 30)
  Move.create(id: 38, name: "Double-Edge", pp: 15)
  Move.create(id: 37, name: "Thrash", pp: 20)
  Move.create(id: 36, name: "Take Down", pp: 20)
  Move.create(id: 35, name: "Wrap", pp: 20)
  Move.create(id: 34, name: "Body Slam", pp: 15)
  Move.create(id: 33, name: "Tackle", pp: 35)
  Move.create(id: 32, name: "Horn Drill", pp: 5)
  Move.create(id: 31, name: "Fury Attack", pp: 20)
  Move.create(id: 30, name: "Horn Attack", pp: 25)
  Move.create(id: 29, name: "Headbutt", pp: 15)
  Move.create(id: 28, name: "Sand Attack", pp: 15)
  Move.create(id: 27, name: "Rolling Kick", pp: 15)
  Move.create(id: 26, name: "Jump Kick", pp: 25)
  Move.create(id: 25, name: "Mega Kick", pp: 5)
  Move.create(id: 24, name: "Double Kick", pp: 30)
  Move.create(id: 23, name: "Stomp", pp: 20)
  Move.create(id: 22, name: "Vine Whip", pp: 10)
  Move.create(id: 21, name: "Slam", pp: 20)
  Move.create(id: 20, name: "Bind", pp: 20)
  Move.create(id: 19, name: "Fly", pp: 15)
  Move.create(id: 18, name: "Whirlwind", pp: 20)
  Move.create(id: 17, name: "Wing Attack", pp: 35)
  Move.create(id: 16, name: "Gust", pp: 35)
  Move.create(id: 15, name: "Cut", pp: 30)
  Move.create(id: 14, name: "Swords Dance", pp: 20)
  Move.create(id: 13, name: "Razor Wind", pp: 10)
  Move.create(id: 12, name: "Guillotine", pp: 5)
  Move.create(id: 11, name: "Vice Grip", pp: 30)
  Move.create(id: 10, name: "Scratch", pp: 35)
  Move.create(id: 9, name: "Thunder Punch", pp: 15)
  Move.create(id: 8, name: "Ice Punch", pp: 15)
  Move.create(id: 7, name: "Fire Punch", pp: 15)
  Move.create(id: 6, name: "Pay Day", pp: 20)
  Move.create(id: 5, name: "Mega Punch", pp: 20)
  Move.create(id: 4, name: "Comet Punch", pp: 15)
  Move.create(id: 3, name: "Double Slap", pp: 10)
  Move.create(id: 2, name: "Karate Chop", pp: 25)
  Move.create(id: 1, name: "Pound", pp: 35)
end
